import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import ColorProvider from "./providers/colors/ColorProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ColorProvider>
      <html lang="en" >
        <body suppressHydrationWarning={true} className={inter.className}>{children}</body>
      </html>
    </ColorProvider>
  );
}
